
auth.token=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

defaults.org=personal-2qu
defaults.project=tribe

defaults.url=https://sentry.io/
